
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getStories() : Promise<Result<StoryListing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addStory(name: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_story", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStory(id: number) : Promise<Result<Story, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_story", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStoryOutline(id: number) : Promise<Result<StoryOutline, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_story_outline", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteStory(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_story", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async patchStory(patch: StoryPatch) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patch_story", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportStoryToml(storyId: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_story_toml", { storyId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importStoryToml(tomlContent: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_story_toml", { tomlContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTomlSchema() : Promise<string> {
    return await TAURI_INVOKE("get_toml_schema");
},
async getPage(id: number) : Promise<Result<Page, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_page", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async patchPage(patch: PagePatch) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patch_page", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPage(storyId: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_page", { storyId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createChoice(pageId: number, text: string, targetPageId: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_choice", { pageId, text, targetPageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteChoice(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_choice", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async patchChoice(patch: ChoicePatch) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patch_choice", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStoryFlags(storyId: number) : Promise<Result<Flag[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_story_flags", { storyId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFlag(create: CreateFlag) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_flag", { create }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async patchFlag(patch: FlagPatch) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("patch_flag", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFlag(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_flag", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFlagOperation(op: SetFlagOperation) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_flag_operation", { op }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeFlagOperation(choiceId: number | null, pageId: number | null, flagId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_flag_operation", { choiceId, pageId, flagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChoiceFlagOperations(choiceId: number) : Promise<Result<FlagOperation[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_choice_flag_operations", { choiceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPageFlagOperations(pageId: number) : Promise<Result<FlagOperation[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_page_flag_operations", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setChoiceCondition(cond: SetChoiceCondition) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_choice_condition", { cond }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeChoiceCondition(choiceId: number, flagId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_choice_condition", { choiceId, flagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChoiceConditions(choiceId: number) : Promise<Result<ChoiceCondition[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_choice_conditions", { choiceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Choice = { id: number; page_id: number; text: string; target_page: number; flag_operations: FlagOperation[]; conditions: ChoiceCondition[] }
export type ChoiceCondition = { id: number; flag_id: number; required_value: boolean }
export type ChoicePatch = { id: number; text: string | null; target_page: number | null }
export type CreateFlag = { story_id: number; name: string; default_value: boolean }
export type Flag = { id: number; story_id: number; name: string; default_value: boolean }
export type FlagOperation = { id: number; flag_id: number; operation: string }
export type FlagPatch = { id: number; name: string | null; default_value: boolean | null }
export type Page = { id: number; story_id: number; name: string; body: string; options: Choice[]; flag_operations: FlagOperation[] }
export type PageListItem = { id: number; name: string }
export type PagePatch = { id: number; name: string | null; body: string | null }
export type SetChoiceCondition = { choice_id: number; flag_id: number; required_value: boolean }
export type SetFlagOperation = { choice_id: number | null; page_id: number | null; flag_id: number; operation: string }
export type Story = { id: number; title: string; pages: Page[]; start_page: number }
export type StoryListing = { id: number; title: string }
export type StoryOutline = { id: number; title: string; pages: PageListItem[]; start_page: number }
export type StoryPatch = { id: number; title: string | null; start_page: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
