// ts-rs emits one file per type and no index. This regenerates the barrel
// from whatever is actually in src/, so a newly derived type cannot be
// forgotten — a hand-written index would be exactly the drift this package
// exists to prevent.
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "src");

const names = readdirSync(srcDir)
  .filter((f) => f.endsWith(".ts"))
  .map((f) => f.replace(/\.ts$/, ""))
  .sort();

const body = [
  "// Generated by types/generate-index.mjs. Do not edit this file manually.",
  ...names.map((n) => `export type { ${n} } from "./src/${n}";`),
  "",
].join("\n");

writeFileSync(join(here, "index.ts"), body);
console.log(`types: indexed ${names.length} generated types`);
