// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Inline } from "./Inline";

export type Block = { "type": "paragraph", content: Array<Inline>, } | { "type": "blockquote", content: Array<Block>, } | { "type": "image", src: string, alt: string, } | { "type": "horizontal_rule" } | { "type": "markdown", source: string, };
