// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { FlagOperation } from "./FlagOperation";

export type Choice = { id: string, text: string, target: string, flag_operations: Array<FlagOperation>, conditions: Array<Condition>, };
