// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IncomingReference } from "./IncomingReference";

/**
 * What deleting one page would break, for the confirmation dialog.
 *
 * Deliberately carries no count of the page's OWN choices: those leave with
 * the page and are not damage to warn about. Only two things are: losing the
 * story's entry point, and stranding choices on other pages.
 */
export type DeleteImpact = { page_id: string, 
/**
 * Empty when the id names no live page.
 */
page_name: string, is_start_page: boolean, 
/**
 * Live pages holding a choice that targets this page, in page order.
 * A page's choice targeting itself is excluded — it leaves with the page.
 */
incoming: Array<IncomingReference>, };
