// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

/**
 * Authoring-only state attached to a page. Never reaches a reader:
 * `build_manifest` clears it when packing a bundle.
 *
 * This is a general slot, not a position field with extra steps — the next
 * authoring-only concern (collapsed state, colour tags) belongs here too.
 */
export type EditorMetadata = { position?: Position | null, };
