// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlagOperation = { flag_id: string, 
/**
 * Genuinely a `String` in Rust today, not a real enum — the `#[ts(type
 * = ...)]` override below asserts the literal union the TypeScript side
 * has always relied on. Making this a proper enum is a data-model
 * change for another day; until then, this override is what keeps the
 * generated type honest with the contract consumers already assume.
 */
operation: "set_true" | "set_false" | "toggle", };
