// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Player-facing save format, shared by the player engine and the reader's
 * on-disk save slots.
 *
 * These three types serialise in camelCase, unlike every other type in this
 * crate. That is deliberate and load-bearing: the player's TypeScript has
 * always used camelCase here, and the renames are what let the generated
 * bindings match it exactly. Normalising the wire format is tracked
 * separately in docs/TODO.md.
 */
export type GameState = { currentPageId: string, flags: { [key in string]: boolean }, };
