// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphEdge = { id: string, source: string, target: string, label: string, 
/**
 * True when `target` names no existing page. Kept rather than dropped:
 * a choice that leads nowhere is exactly what the author needs to see.
 */
is_dangling: boolean, };
