// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

export type GraphNode = { id: string, name: string, is_start: boolean, 
/**
 * Author-placed position, if any. Absent nodes get an automatic layout.
 */
position: Position | null, };
