// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A choice on some other page that points at the page being deleted.
 */
export type IncomingReference = { page_id: string, page_name: string, choice_id: string, choice_text: string, };
