// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";
import type { ManifestStory } from "./ManifestStory";
import type { Page } from "./Page";

/**
 * The bundle manifest — a self-contained story with all pages inline.
 */
export type Manifest = { format_version: number, story: ManifestStory, flags: Array<Flag>, pages: Array<Page>, };
