// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";
import type { Document } from "./Document";
import type { FlagOperation } from "./FlagOperation";

export type Page = { id: string, name: string, body: Document, choices: Array<Choice>, flag_operations: Array<FlagOperation>, };
