// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PageListItem = { id: string, name: string, 
/**
 * Copied from the page so the trash list can sort by recency without
 * reading every trashed page in full.
 */
last_modified?: string | null, };
