// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is wrong, as a machine-readable code plus the fields the UI needs to
 * build a sentence. Deliberately carries no prose: all user-facing wording
 * lives in the frontend's translations file.
 */
export type ProblemDetail = { "code": "dangling_choice_target", choice_id: string, choice_text: string, target: string, } | { "code": "dangling_page_flag_operation", flag_id: string, } | { "code": "dangling_choice_flag_operation", choice_id: string, choice_text: string, flag_id: string, } | { "code": "dangling_choice_condition", choice_id: string, choice_text: string, flag_id: string, } | { "code": "start_page_unset" } | { "code": "start_page_missing", start_page: string, } | { "code": "unreachable_page" };
