// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemDetail } from "./ProblemDetail";
import type { Severity } from "./Severity";

export type Problem = { severity: Severity, 
/**
 * Page this problem belongs to. `None` for story-level problems.
 */
page_id: string | null, 
/**
 * Page name at validation time, so the UI need not look it up.
 */
page_name: string | null, detail: ProblemDetail, };
