// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";

export type SavedState = { gameState: GameState, name: string, timestamp: bigint, };
