// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How serious a problem is. Only `Error` blocks export.
 *
 * Declaration order is the display order — `derive(Ord)` sorts `Error`
 * first. `Info` is plumbed end to end but no current rule emits it.
 */
export type Severity = "error" | "warning" | "info";
