// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlotInfo = { slotId: string, name: string, 
/**
 * `u64` in Rust, but serde_json serialises it as a plain JSON number —
 * the override reflects what actually crosses the wire, not ts-rs's
 * default `bigint` mapping for 64-bit integers.
 */
timestamp: number, };
