// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flag } from "./Flag";

export type Story = { format_version: number, 
/**
 * Stable identity for this story, preserved into exported bundles so a
 * reader can tell two stories apart. Defaults to empty for story.json
 * files written before ids existed; `Project::open` backfills those.
 */
id: string, title: string, start_page: string, flags: Array<Flag>, };
