[package]
name = "creation-tool"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = ["protocol-asset"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
shared = { path = "../../shared" }
thiserror = "2.0.20"
tauri-plugin-dialog = "2.7.2"
tauri-plugin-fs = "2.5.1"
axum = { version = "0.8", optional = true }
tower-http = { version = "0.7", features = ["cors"], optional = true }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
test-server = ["axum", "tower-http"]

[dev-dependencies]
tempfile = "3.27"
