// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceCondition } from "./ChoiceCondition";
import type { FlagOperation } from "./FlagOperation";

export type Choice = { id: bigint, page_id: bigint, text: string, target_page: bigint, flag_operations: Array<FlagOperation>, conditions: Array<ChoiceCondition>, };
