// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Flag = { id: bigint, story_id: bigint, name: string, default_value: boolean, };
