// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";
import type { FlagOperation } from "./FlagOperation";

export type Page = { id: bigint, story_id: bigint, name: string, body: string, options: Array<Choice>, flag_operations: Array<FlagOperation>, };
