// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Page } from "./Page";

export type Story = { id: bigint, title: string, pages: Array<Page>, start_page: bigint, };
