// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageListItem } from "./PageListItem";

export type StoryOutline = { id: bigint, title: string, pages: Array<PageListItem>, start_page: bigint, };
